#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Wait for telegraf
s6-svwait -U /run/s6/services/telegraf

# Build the readsb command line based on options
READSB_BIN="/usr/local/bin/readsb"
READSB_CMD=(--net-only)
READSB_CMD+=(--quiet)
READSB_CMD+=("--net-connector=${ADSBHOST},${ADSBPORT},${ADSBTYPE}")
if [ -n "${MLATHOST}" ]; then
    READSB_CMD+=("--net-connector=${MLATHOST},${MLATPORT},beast_in")
fi
READSB_CMD+=(--stats-every=3600)
READSB_CMD+=("--net-json-port ${JSONPORT}")
READSB_CMD+=(--write-json-globe-index)
READSB_CMD+=("--json-trace-interval ${INTERVAL}")
READSB_CMD+=("--net-connector=127.0.0.1,30013,json_out")

# Run readsb
"${READSB_BIN}" "${READSB_CMD[@]}" 2>&1 | awk -W Interactive '{print "[readsb] " $0}'
