#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Check to make sure the correct command line arguments have been set
EXITCODE=0
echo -ne "\e[31m"
if [ -z "${INFLUXDBURL+x}" ]; then
  echo "ERROR: INFLUXDBURL environment variable not set"
  EXITCODE=1
fi
if [ -z "${ADSBHOST+x}" ]; then
  echo "ERROR: ADSBHOST environment variable not set"
  EXITCODE=1
fi
if [ -z "${INFLUXDB_USERNAME+x}" ]; then
  if [ ! -z "${INFLUXDB_PASSWORD+x}" ]; then
    echo "ERROR: Please also set environment variable INFLUXDB_USERNAME"
    EXITCODE=1
  fi
fi
if [ -z "${INFLUXDB_PASSWORD+x}" ]; then
  if [ ! -z "${INFLUXDB_USERNAME+x}" ]; then
    echo "ERROR: Please also set environment variable INFLUXDB_PASSWORD"
    EXITCODE=1
  fi
fi

echo -ne "\e[0m"
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -ne "\e[33m"
  echo "WARNING: TZ environment variable not set"
  echo -ne "\e[0m"
else
  ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
fi
