#!/usr/bin/with-contenv bash
#shellcheck shell=bash

CONFIG_FILE="/etc/telegraf/telegraf.d/outputs_influxdb.conf"

# Build telegraf config
{
  echo "[[outputs.influxdb]]"

  # Add InfluxDB URL
  echo " urls = [\"${INFLUXDBURL}\"]"

  # Finish config
  echo 'database = "adsb"'
  echo 'skip_database_creation = false'
  echo 'timeout = "5s"'

  # If set, add InfluxDB username
  if [ -n "${INFLUXDBUSERNAME+x}" ]; then
    echo "username = \"${INFLUXDBUSERNAME}\""
  fi

  # If set, add InfluxDB password
  if [ -n "${INFLUXDBPASSWORD+x}" ]; then
    echo "password = \"${INFLUXDBPASSWORD}\""
  fi

} > ${CONFIG_FILE}